import { useEffect, useState } from 'react'
import { fetchVariantConfig } from '../api.ts'

/** The server renders only the current fixture. No scenario or behaviour table is shipped here. */
export function ProductSearch({ onQueryChange }: { onQueryChange: (query: string) => void }) {
  const [html, setHtml] = useState<string | null>(null)
  useEffect(() => {
    let active = true
    void fetchVariantConfig().then((config) => {
      if (active) setHtml(config.search?.html ?? null)
    })
    return () => {
      active = false
    }
  }, [])
  if (html === null) return null
  return (
    <div
      // HTML is generated by our own same-origin server from static React templates, never user text.
      dangerouslySetInnerHTML={{ __html: html }}
      onInput={(event) => {
        if (event.target instanceof HTMLInputElement) onQueryChange(event.target.value)
      }}
      onClick={(event) => {
        if (!(event.target instanceof Element) || !event.target.closest('button')) return
        const input = event.currentTarget.querySelector('input')
        if (input) {
          input.value = ''
          onQueryChange('')
        }
      }}
    />
  )
}
